- src/Message/AbstractRequest.php
- tests/Message/CaptureRequestTest.php
PayPal partner codes (BN Codes) are passed to PayPal Express Checkout by passing an additional parameter with the base data.
This adds simple accessors and adds to the base data unit tests to cover the new code.
> Add support for passing BN Codes

- src/Message/RestAuthorizeResponse.php
- src/Message/RestCompletePurchaseRequest.php
- src/Message/RestPurchaseRequest.php
I have added docblocks to the newly added code for completing paypal payments.  I also removed a now-obsolete piece of documentation stating that the purchase request does not support paypal payments (which it now does).
There are no code changes contained in this PR, only documentation and comment changes.
> Adding and fixing docblocks

- src/Message/ExpressCompleteAuthorizeRequest.php
- tests/Message/ExpressCompleteAuthorizeRequestTest.php
- tests/Message/ExpressCompletePurchaseRequestTest.php
As described here https://github.com/thephpleague/omnipay-paypal/issues/45, if we send other amounts like shipping handling charges, discounts etc during authorization, that data needs to be set during complete purchase also. Otherwise we get error `Item total is not equal to order total`
> send all other amounts along for complete purchase

- src/Message/ExpressAuthorizeResponse.php
- tests/ExpressGatewayTest.php
- tests/Message/ExpressAuthorizeResponseTest.php
...for the ExpressAuthorizeResponse class.
See the [documentation](https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECGettingStarted/).
> Adding /cgi-bin/ to live and testCheckoutEndpoint path

- src/ExpressGateway.php
- src/Message/ExpressVoidRequest.php
- src/Message/Response.php
- tests/ExpressGatewayTest.php
- tests/Message/ExpressVoidRequestTest.php
- tests/Mock/ExpressVoidFailure.txt
- tests/Mock/ExpressVoidSuccess.txt
This re-implements the addition of void to PayPal Express as first created by @alexw23 on PR #58 . I had originally intended to implement a void message in PayPal REST but I had mis-read the PayPal REST documentation, and voiding payments that have already been captured is not possible with REST.
This also fixes the formatting issues and adds test cases and mocks for void.
A PR to add documentation to the PayPal Express gateway and message code will follow some time later.
> Implement void

- src/Message/AbstractRequest.php
- tests/Message/ExpressAuthorizeRequestTest.php
Requests resultet mostly in errors like this because the request-parameter "PAYMENTREQUEST_0_ITEMAMT" was not correctly formatted to a string.
Response-Data:
```
{
"TIMESTAMP": "2015-05-06T08:49:11Z",
"CORRELATIONID": "...",
"ACK": "Failure",
"VERSION": "85.0",
"BUILD": "16566018",
"L_ERRORCODE0": "10426",
"L_SHORTMESSAGE0": "Transaction refused because of an invalid argument. See additional error messages for details.",
"L_LONGMESSAGE0": "Item total is invalid.",
"L_SEVERITYCODE0": "Error"
}
```
Request-Data:
```
{
"VERSION": "85.0",
"USER": "...",
"PWD": "...",
"SIGNATURE": "...",
"SUBJECT": null,
"METHOD": "SetExpressCheckout",
"PAYMENTREQUEST_0_PAYMENTACTION": "Authorization",
"PAYMENTREQUEST_0_AMT": "24.90",
"PAYMENTREQUEST_0_CURRENCYCODE": "EUR",
"PAYMENTREQUEST_0_INVNUM": null, …
```
> Added formatCurrency to avoid API error message 'Item total is invalid.'

- src/Message/RestRefundRequest.php
array() will make json_encode() return [] instead of {} which PayPal expects when doing full refund without specifying amount
> REST Refund without amount

- src/Message/AbstractRestRequest.php
- src/Message/RestAuthorizeResponse.php
- src/Message/RestCancelSubscriptionRequest.php
- src/Message/RestCompleteSubscriptionRequest.php
- src/Message/RestCreatePlanRequest.php
- src/Message/RestCreateSubscriptionRequest.php
- src/Message/RestReactivateSubscriptionRequest.php
- src/Message/RestRefundRequest.php
- src/Message/RestSearchTransactionRequest.php
- src/Message/RestSuspendSubscriptionRequest.php
- src/Message/RestUpdatePlanRequest.php
- src/RestGateway.php
- tests/Message/RestCancelSubscriptionRequestTest.php
- tests/Message/RestCompleteSubscriptionRequestTest.php
- tests/Message/RestCreatePlanRequestTest.php
- tests/Message/RestCreateSubscriptionRequestTest.php
- tests/Message/RestFetchTransactionRequestTest.php
- tests/Message/RestReactivateSubscriptionRequestTest.php
- tests/Message/RestSearchTransactionRequestTest.php
- tests/Message/RestSuspendSubscriptionRequestTest.php
- tests/Message/RestUpdatePlanRequestTest.php
- tests/Mock/RestExecuteSubscriptionSuccess.txt
- tests/Mock/RestGenericSubscriptionSuccess.txt
- tests/RestGatewayTest.php
This PR implements billing plans and agreements (subscriptions) in the PayPal REST gateway.  Although Omnipay does not in the general case implement subscriptions, preferring to use card tokens to allow subscriptions to be managed by the application, in the case of PayPal payments from a customer's PayPal account subscriptions cannot be implemented that way.
This is not complete yet -- there are a few functions missing such as Update/Cancel/Suspend/Reactivate agreement, but I have chosen to push this PR now to create an API definition for the basic functions required to create working subscriptions.
The function names chosen are identical to those in the Stripe gateway, which also handles subscriptions, although the parameter structure is necessarily different.
All functions have tests …
> Implement recurring payments

- src/Message/AbstractRestRequest.php
- src/Message/RestFetchPurchaseRequest.php
- src/Message/RestListPurchaseRequest.php
- src/RestGateway.php
- tests/Message/RestFetchPurchaseRequestTest.php
- tests/Mock/RestFetchPurchaseSuccess.txt
- tests/RestGatewayTest.php
This PR implements queries on the PayPal payment resources. 2 additional gateway methods are available: fetchPurchase and listPurchase. As opposed to fetchTransaction these operate on any type of transaction, not just completed transactions.
These methods are often the only way that an application can determine that PayPal has completed a purchase in the event of, for example, the customer's browser crashing or the customer closing their browser between the customer authorizing the payment at the PayPal gateway and returning via the returnUrl to the merchant's web site.
> Implement payment queries

- tests/RestGatewayTest.php
- changes in 2a2191f705b43986b0647a2d0143c3052745199a fixed
issue by returning '{}' which is what PayPal expects for a refund
> Update test to check for empty object instead of just empty

- src/Message/AbstractRestRequest.php
This PR adds an exception handler so that guzzle errors communicating with the gateway will be translated to the Omnipay exception (InvalidReseponseException). Without this handler the calling code becomes reliant on guzzle.
> Adding exception handler, mostly for catching guzzle errors

- src/Message/ExpressAuthorizeRequest.php
- src/Support/InstantUpdateApi/ShippingOption.php
- tests/Message/ExpressAuthorizeRequestTest.php
Add support for PayPal's Instant Update API shipping costs calculator
* it requires you to send PayPal a callback URL
* if you send a callback URL, you must also specify its timeout and default shipping options
* on line 115 where we check for `if (!empty($shippingOptions))` it arguably should throw an `InvalidArgumentException` or similar - the rest of the library doesn't do this, so I have left it as is to be consistent with the current behaviour
* included a test as per the contribution guidelines, please let me know if more is required
> Add support for Instant Update API Callback

- src/Message/AbstractRequest.php
- src/Message/AbstractRestRequest.php
for Operating Systems without TLS v1.2 bundled by default (CentOS 6.7 for example)
> Add support for TLS v1.2

- src/Message/AbstractRequest.php
With previous post request formulation there is an Paypal Error 81002 (Method is not supported).
> Make post request work properly

- src/Message/AbstractRequest.php
Only call `getCode` if the item is a PayPalItem instance.
fix for: 
- https://github.com/thephpleague/omnipay/issues/379
- https://github.com/thephpleague/omnipay-paypal/issues/135
> check item class

- src/Message/RestAuthorizeResponse.php
The endpoint billing agreements terminates with "agreement-execute" not "execute", therefore the transaction reference was not being returned.
https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_create_response
> Fix the transaction ID retrieval for billing agreements

- README.md
Adds a note in readme that packages supports In-Context too. See #142 and #144.
> Add supported ExpressInContext

- src/Message/ExpressAuthorizeRequest.php
- src/Support/InstantUpdateApi/BillingAgreement.php
- tests/Message/ExpressAuthorizeRequestTest.php
- tests/ProGatewayTest.php
- tests/RestGatewayTest.php
Refference Transaction is feature of Express Checkout used for recurring payments of varying amounts of money on a varying schedule.
https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECReferenceTxns/
https://developer.paypal.com/docs/classic/express-checkout/ec_set_up_reference_transactions/
>  added support for reference transaction in express checkout

- src/Message/AbstractRequest.php
At PayPal items can be negativ. We need to allow negativ amounts
> Allow negative amount for items

- src/Message/RestTokenRequest.php
Currently REST gateway calls will fail, because the gateway is unable to fetch a valid access token. 
The `/oauth2/token` endpoint expects a Authentication Basic header [(docs)](https://developer.paypal.com/docs/api/overview/#get-an-access-token).
Tested in production.
> Authentication fix for getting a REST gateway access token

- tests/Mock/RestGenericSubscriptionSuccess.txt
`GuzzleHttp\Psr7\_parse_message` isn't able to parse `RestGenericSubscriptionSuccess.txt` because the message has no content in `RestGatewayTest` (https://travis-ci.org/thephpleague/omnipay-paypal/jobs/489941682#L601). This PR adds content to the message so the tests no longer fail.
> Adds content to the success message mock

- src/Message/AbstractRestRequest.php
Referrer code is otherwise called BNCode or partner attribution id in paypal-land.
I chose referrer code as something generic
https://developer.paypal.com/docs/integration/direct/payments/#
> #216 Add support for referrer code to Rest Gateway

- src/Message/AbstractRestRequest.php
Allow negative Amount Items for REST Api too same as for the other API like here requested: https://github.com/thephpleague/omnipay-paypal/pull/198
> allow negative items for REST API
